/* 英语·语法诊断与长难句拆解数据
   每条：en 原句 / zh 译文 / grammar 语法点标签 / trunk 主干 / modifiers 修饰 / point 语法讲解 / imitate 仿写示例
   专升本高频难点：虚拟语气 / 倒装 / 定语从句 / 非谓语动词 */
window.ENG_SYNTAX = [
  /* ===== 虚拟语气 ===== */
  { en: 'If I were you, I would take the job immediately.', zh: '如果我是你，我会立刻接受这份工作。', grammar: '虚拟语气',
    trunk: 'I would take the job.', modifiers: 'If I were you（条件从句，与现在事实相反）/ immediately（状语）',
    point: '与现在事实相反的虚拟：if 从句用 were（无论人称），主句用 would/could/should + 动词原形。were 不可写成 was。',
    imitate: '仿写：如果我有更多时间，我会读完这本书。→ If I had more time, I would finish this book.' },
  { en: 'Had we left earlier, we would have caught the train.', zh: '如果我们早点出发，就能赶上火车了。', grammar: '虚拟语气',
    trunk: 'we would have caught the train.', modifiers: 'Had we left earlier（= If we had left earlier，省略 if 引起倒装）',
    point: '与过去事实相反：if 从句 had done，主句 would have done。省略 if 时 had 提前构成倒装（Had we left = If we had left）。',
    imitate: '仿写：如果你复习了，你就能通过考试。→ Had you reviewed, you would have passed the exam.' },
  { en: 'The teacher suggests that we (should) hand in the paper next Monday.', zh: '老师建议我们下周一交论文。', grammar: '虚拟语气',
    trunk: 'The teacher suggests that we hand in the paper.', modifiers: 'next Monday（时间状语）',
    point: '表示“建议、要求、命令”的动词（suggest/insist/demand/request）后接 that 从句，谓语用 (should) + 动词原形（虚拟语气）。',
    imitate: '仿写：他要求我们都参加。→ He demands that we (should) all attend.' },
  { en: 'Without your help, I could not have succeeded.', zh: '没有你的帮助，我不可能成功。', grammar: '虚拟语气',
    trunk: 'I could not have succeeded.', modifiers: 'Without your help（含蓄虚拟，相当于 If there had been no your help）',
    point: 'without / but for 等介词短语可表达含蓄条件，与过去相反时用 could/would have done。',
    imitate: '仿写：没有水，植物就无法生长。→ Without water, plants could not grow.' },

  /* ===== 倒装 ===== */
  { en: 'Never have I seen such a beautiful sunset.', zh: '我从未见过如此美丽的日落。', grammar: '倒装',
    trunk: 'I have seen such a beautiful sunset.', modifiers: 'Never（否定副词置于句首引起部分倒装）/ such a beautiful（定语）',
    point: '否定副词（never/little/seldom/hardly）置于句首，主句需部分倒装：助动词 have 提到主语 I 前。',
    imitate: '仿写：我几乎不记得那件事。→ Seldom do I remember that matter.' },
  { en: 'Not only did he finish the work, but he also helped others.', zh: '他不但完成了工作，还帮助了别人。', grammar: '倒装',
    trunk: 'he finished the work / he helped others.', modifiers: 'Not only（置于句首引起前半句倒装）/ also（后半句不倒装）',
    point: 'not only...but also... 中，not only 置于句首时其所在分句部分倒装，but also 后不倒装。',
    imitate: '仿写：她不仅来了，还带了礼物。→ Not only did she come, but she also brought a gift.' },
  { en: 'Only by working hard can we achieve our goals.', zh: '只有通过努力，我们才能实现目标。', grammar: '倒装',
    trunk: 'we can achieve our goals.', modifiers: 'Only by working hard（only + 介词短语置于句首）',
    point: '“only + 状语”置于句首，主句部分倒装：can 提到 we 前。注意 only 修饰主语时不倒装。',
    imitate: '仿写：只有这样我们才能赢。→ Only in this way can we win.' },
  { en: 'So tired was he that he fell asleep at once.', zh: '他太累了，以至于立刻睡着了。', grammar: '倒装',
    trunk: 'he was tired / he fell asleep.', modifiers: 'So tired（so 置于句首引起倒装）/ that he fell asleep at once（结果状语从句）',
    point: '“so + 形容词/副词”置于句首，主句部分倒装：was 提到 he 前。',
    imitate: '仿写：她跑得如此之快，没人追上她。→ So fast did she run that no one caught up.' },

  /* ===== 定语从句 ===== */
  { en: 'The book that/which you borrowed yesterday is very useful.', zh: '你昨天借的那本书很有用。', grammar: '定语从句',
    trunk: 'The book is very useful.', modifiers: 'that/which you borrowed yesterday（定语从句修饰 book）',
    point: '先行词 book 指物，用 that 或 which 引导；从句缺宾语可省略关系词。borrowed 后省略了 it/them。',
    imitate: '仿写：我昨天买的那件衣服很便宜。→ The dress (that/which) I bought yesterday is cheap.' },
  { en: 'The girl whose father is a doctor won the prize.', zh: '父亲是医生的那个女孩获奖了。', grammar: '定语从句',
    trunk: 'The girl won the prize.', modifiers: 'whose father is a doctor（whose 表所属，修饰 girl）',
    point: 'whose 在从句中作定语，表示“……的”，可指人或物。此处 whose father = the girl’s father。',
    imitate: '仿写：屋顶是红色的房子是我的。→ The house whose roof is red is mine.' },
  { en: 'This is the city where I was born.', zh: '这是我出生的城市。', grammar: '定语从句',
    trunk: 'This is the city.', modifiers: 'where I was born（where = in which，作地点状语）',
    point: '先行词表地点且从句缺状语时用 where；若从句缺主语/宾语则用 that/which。区别：This is the city that we visited.（缺宾用 that）',
    imitate: '仿写：这就是我们上周开会的地方。→ This is the place where we held the meeting last week.' },
  { en: 'He is the only one of the students who has passed the exam.', zh: '他是学生中唯一通过考试的人。', grammar: '定语从句',
    trunk: 'He is the only one.', modifiers: 'who has passed the exam（定语从句修饰 the only one）',
    point: '“the only one of + 复数名词”后的定语从句谓语用单数 has；若是“one of + 复数名词”则常用复数 have。',
    imitate: '仿写：她是唯一懂法语的老师。→ She is the only one of the teachers who knows French.' },

  /* ===== 非谓语动词 ===== */
  { en: 'Given more time, we could have done it better.', zh: '如果给更多时间，我们本可以做得更好。', grammar: '非谓语动词',
    trunk: 'we could have done it better.', modifiers: 'Given more time（过去分词作条件状语，= If we had been given more time）',
    point: 'given 作介词/分词，引出已给条件，相当于 if 从句。过去分词表被动、完成。',
    imitate: '仿写：考虑到他的年龄，他做得很好。→ Considering his age, he did a good job.' },
  { en: 'The boy sitting by the window is my brother.', zh: '坐在窗边的男孩是我弟弟。', grammar: '非谓语动词',
    trunk: 'The boy is my brother.', modifiers: 'sitting by the window（现在分词短语作后置定语，= who is sitting）',
    point: '现在分词 doing 作定语表主动、进行；过去分词 done 表被动、完成。sit 与 boy 主动进行，用 sitting。',
    imitate: '仿写：那个正在读书的女孩是班长。→ The girl reading a book is the monitor.' },
  { en: 'To master English well, you need daily practice.', zh: '要学好英语，你需要每天练习。', grammar: '非谓语动词',
    trunk: 'you need daily practice.', modifiers: 'To master English well（不定式作目的状语，置于句首表“为了”）',
    point: '不定式 to do 常表目的、将来；放句首时逗号后接主句。',
    imitate: '仿写：为了通过考试，他每天学习。→ To pass the exam, he studies every day.' },
  { en: 'I found the book difficult to understand.', zh: '我发现这本书很难懂。', grammar: '非谓语动词',
    trunk: 'I found the book difficult.', modifiers: 'to understand（不定式作状语，与 book 构成逻辑动宾：to understand the book）',
    point: '“find + 宾语 + 形容词 + to do”结构中，不定式与宾语存在逻辑动宾关系，主动形式表被动意义。',
    imitate: '仿写：我觉得这个问题很难回答。→ I found the question difficult to answer.' }
];
