/* 英语 · 长难句 & 语法（初学者友好） */

/* 15 个语法点：从入门到进阶，每个有 讲解+例句+提示 */
window.ENG_GRAMMAR = [
  { cat: '入门', title: '句子成分与五大基本句型', q: '英语句子由“主语+谓语”核心构成，五大基本句型：主谓、主谓宾、主系表、主谓双宾、主谓宾补。', ex: 'She (主) laughs (谓). / He (主) is (系) a teacher (表).', tip: '先找“谁+干啥/是啥”，这是读懂长句的地基。' },
  { cat: '入门', title: '一般现在时', q: '表示经常发生或客观事实，主语三单时动词加 -s/-es。', ex: 'I read books every day. / He reads books.', tip: '标志词：always, usually, often, every day。' },
  { cat: '入门', title: '一般过去时', q: '表示过去发生的事，规则动词加 -ed，不规则需记。', ex: 'She watched a movie yesterday.', tip: '标志词：yesterday, last week, ago。' },
  { cat: '入门', title: '一般将来时', q: 'will + 动词原形，或 be going to + 动词原形表计划。', ex: 'I will study abroad. / She is going to visit Beijing.', tip: 'will 表意愿/预测；going to 表已有迹象的计划。' },
  { cat: '基础', title: '名词：可数与不可数', q: '可数名词有单复数（加 -s/-es）；不可数名词（水、信息、建议）无复数，不能直接加 a/an。', ex: 'a book / two books；water（不可数），a piece of advice。', tip: '见到 much/little 后接不可数；many/few 后接可数复数。' },
  { cat: '基础', title: '冠词 a / an / the', q: 'a/an 表“一个”（泛指）；the 表“这个/那个”（特指，双方都知道的）。', ex: 'I saw a cat. The cat was black.', tip: '首次提用 a/an，再次提用 the；泛指类别也可用 the。' },
  { cat: '基础', title: '代词', q: '人称（I/you/he）、物主（my/your）、指示（this/that）、不定（some/any）等，避免重复名词。', ex: 'This is my book; it is new.', tip: 'it 常指代前文单数事物；they 指代复数。' },
  { cat: '基础', title: '形容词比较级与最高级', q: '更…：形容词+er（或 more+原级）；最…：+est（或 most+原级）。', ex: 'taller / more beautiful；the tallest / the most beautiful.', tip: '两者比用比较级（than）；三者以上用最高级（the）。' },
  { cat: '基础', title: '介词', q: '表示时间、地点、方式的小词：in/on/at, at/in/to, with/by/for 等。', ex: 'in the morning, on Monday, at school, by bus, with me.', tip: '介词后接名词/代词/动名词（-ing），不接原形动词。' },
  { cat: '基础', title: 'There be 句型', q: '表示“某处有某物”：There is + 单数，There are + 复数。', ex: 'There is a book on the desk. There are many students.', tip: 'be 动词单复数随后面第一个名词，别看远处。' },
  { cat: '基础', title: '情态动词', q: 'can/must/should/may + 动词原形，表能力、必要、建议、可能。', ex: 'You should study hard. He can swim.', tip: '情态动词后永远接动词原形，不变三单。' },
  { cat: '进阶', title: '被动语态', q: 'be + 过去分词，强调“被…”的动作承受者。', ex: 'The book was written by Lu Xun.', tip: '主动变被动：宾语变主语，谓语变 be+done，原主语加 by。' },
  { cat: '进阶', title: '定语从句', q: '用 that/which（指物）、who（指人）引导，修饰前面名词。', ex: 'The book that I bought is interesting.', tip: '从句缺主语用 that/which/who；缺宾语也可省略关系词。' },
  { cat: '进阶', title: '宾语从句', q: '动词/形容词后的 that/whether/what 从句作宾语。', ex: 'I think (that) he is right. I wonder whether it is true.', tip: '陈述语序用 that；是否用 whether/if；缺成分用 what。' },
  { cat: '进阶', title: '非谓语动词', q: 'doing（主动/进行）、done（被动/完成）、to do（目的/将来）作定语/状语，不是谓语。', ex: 'The boy playing basketball is my brother.', tip: '长难句里一堆 -ing/-ed 往往是修饰，不是主干谓语。' }
];

/* 30 个万能句式（先练 5 个必练） */
window.ENG_PATTERNS = [
  { id: 'p1', must: true,  pat: 'It is + adj. + that...',        cn: '（公认事实）', ex: 'It is widely acknowledged that education changes lives.', tip: '作文万能开头，显正式。' },
  { id: 'p2', must: true,  pat: 'Not only... but also...',       cn: '（倒装加分项）', ex: 'Not only does it improve efficiency, but also it reduces cost.', tip: 'not only 后句子要部分倒装（助动词提前）。' },
  { id: 'p3', must: true,  pat: 'The more..., the more...',      cn: '（因果关系）', ex: 'The more we practice, the more confident we become.', tip: '前后都用比较级，越…越…。' },
  { id: 'p4', must: true,  pat: 'So + adj. + that...',           cn: '（结果强调）', ex: 'So serious is the problem that immediate action is required.', tip: 'so 提前引发倒装，强调程度。' },
  { id: 'p5', must: true,  pat: 'What... is...',                 cn: '（主语从句）', ex: 'What we need most is practical experience.', tip: 'What 引导主语从句，作句子主语。' },
  { id: 'p6',  pat: 'There is no doubt that...',      cn: '（毫无疑问）', ex: 'There is no doubt that reading broadens our horizon.', tip: '引出强观点。' },
  { id: 'p7',  pat: 'Only by... can we...',           cn: '（唯有…才，倒装）', ex: 'Only by working hard can we achieve our goals.', tip: 'only+状语置首，句子半倒装。' },
  { id: 'p8',  pat: 'It is high time that...',        cn: '（是时候…了）', ex: 'It is high time that we took action.', tip: 'that 后谓语用过去式表虚拟。' },
  { id: 'p9',  pat: 'As far as I am concerned,...',   cn: '（就我而言）', ex: 'As far as I am concerned, health matters most.', tip: '表达个人观点很自然。' },
  { id: 'p10', pat: 'With the development of...',     cn: '（随着…发展）', ex: 'With the development of technology, life changes fast.', tip: '现象类作文常用起手。' },
  { id: 'p11', pat: 'Every coin has two sides.',     cn: '（事物有两面）', ex: 'Every coin has two sides; so does the Internet.', tip: '利弊分析过渡句。' },
  { id: 'p12', pat: 'On the one hand... On the other...', cn: '（一方面…另一方面）', ex: 'On the one hand it saves time; on the other it costs money.', tip: '对比论证。' },
  { id: 'p13', pat: 'Take... for example.',          cn: '（以…为例）', ex: 'Take China for example, it has made huge progress.', tip: '举例论证 signal 句。' },
  { id: 'p14', pat: 'In my opinion,...',             cn: '（我认为）', ex: 'In my opinion, we should balance study and rest.', tip: '收尾亮观点。' },
  { id: 'p15', pat: 'It is generally believed that...', cn: '（人们普遍认为）', ex: 'It is generally believed that honesty is the best policy.', tip: '引出普遍看法。' },
  { id: 'p16', pat: 'Nothing is more important than...', cn: '（没有比…更重要）', ex: 'Nothing is more important than your health.', tip: '强调最高级。' },
  { id: 'p17', pat: 'The reason why... is that...',  cn: '（…的原因是）', ex: 'The reason why he failed is that he gave up.', tip: '因果解释句。' },
  { id: 'p18', pat: 'Only when... do we...',         cn: '（只有当…才）', ex: 'Only when we persist do we see results.', tip: 'when 引导，半倒装。' },
  { id: 'p19', pat: 'It is adj. of sb. to do...',    cn: '（某人做某事是…的）', ex: 'It is wise of you to plan ahead.', tip: '评价人用 of，评价事用 for。' },
  { id: 'p20', pat: 'No matter how..., ...',         cn: '（无论怎样）', ex: 'No matter how hard it is, we won\'t give up.', tip: '让步状语从句。' },
  { id: 'p21', pat: 'Had it not been for...',        cn: '（若不是因为，虚拟）', ex: 'Had it not been for your help, I would have failed.', tip: '虚拟倒装，书面感强。' },
  { id: 'p22', pat: 'What impresses me most is...',  cn: '（最让我印象深刻的是）', ex: 'What impresses me most is his perseverance.', tip: '主语从句引出重点。' },
  { id: 'p23', pat: 'It occurs to me that...',       cn: '（我突然想到）', ex: 'It occurs to me that we forgot the book.', tip: '引出想法。' },
  { id: 'p24', pat: 'Be it... or..., ...',           cn: '（无论…还是，让步）', ex: 'Be it rain or shine, he keeps running.', tip: '让步倒装，较书面。' },
  { id: 'p25', pat: 'The fact that... cannot be ignored.', cn: '（…的事实不容忽视）', ex: 'The fact that climate is changing cannot be ignored.', tip: 'that 同位语从句。' },
  { id: 'p26', pat: 'Not until... did...',           cn: '（直到…才，倒装）', ex: 'Not until midnight did he finish the paper.', tip: 'not until 置首，半倒装。' },
  { id: 'p27', pat: 'A is to B what C is to D.',     cn: '（A 之于 B 犹如 C 之于 D）', ex: 'Reading is to mind what food is to body.', tip: '类比金句。' },
  { id: 'p28', pat: 'Were it not for...',            cn: '（若非，虚拟）', ex: 'Were it not for the teacher, I couldn\'t pass.', tip: 'were 提前虚拟倒装。' },
  { id: 'p29', pat: 'It is no exaggeration to say that...', cn: '（毫不夸张地说）', ex: 'It is no exaggeration to say that books shape us.', tip: '强调开头。' },
  { id: 'p30', pat: 'Where there is..., there is...', cn: '（哪里有…哪里就有）', ex: 'Where there is a will, there is a way.', tip: '谚语式结构。' }
];

/* 50 个长难句（剥洋葱结构：trunk 主干 / peel 剥修饰 / zh 中文） */
window.ENG_SENTENCES = [
  { en: 'Although it was raining heavily, we decided to go for a walk in the park.', zh: '尽管雨下得很大，我们还是决定去公园散步。', trunk: 'we decided to go', peel: 'Although it was raining heavily 是让步状语从句，修饰 decided。' },
  { en: 'The book that I borrowed from the library is very interesting.', zh: '我从图书馆借的那本书很有趣。', trunk: 'The book is interesting', peel: 'that I borrowed from the library 是定语从句，修饰 book。' },
  { en: 'It is important for us to learn a foreign language well.', zh: '对我们来说，学好一门外语很重要。', trunk: 'It is important', peel: 'for us 是逻辑主语；to learn... 是真正主语（it 为形式主语）。' },
  { en: 'The girl sitting by the window is my cousin who just came back from London.', zh: '坐在窗边的那个女孩是我刚从伦敦回来的表妹。', trunk: 'The girl is my cousin', peel: 'sitting by the window 现在分词作定语；who... 定语从句修饰 cousin。' },
  { en: 'Because he was tired, he went to bed earlier than usual last night.', zh: '因为他累了，昨晚他比平时早睡。', trunk: 'he went to bed', peel: 'Because he was tired 原因状语从句；earlier than usual 比较状语。' },
  { en: 'What we need most is practical experience rather than empty talk.', zh: '我们最需要的是实践经验，而不是空谈。', trunk: 'What we need is experience', peel: 'What we need most 主语从句；rather than empty talk 对比状语。' },
  { en: 'The manager asked the employees to finish the report before Friday.', zh: '经理要求员工周五前完成报告。', trunk: 'The manager asked the employees', peel: 'to finish... 不定式作宾补（ask sb to do）。' },
  { en: 'Not only did she pass the exam, but she also got the highest score.', zh: '她不仅通过了考试，还拿了最高分。', trunk: 'she passed and got the score', peel: 'Not only 置首引发半倒装（did she pass）；but also 并列。' },
  { en: 'The city where I was born has changed a lot over the past twenty years.', zh: '我出生的那座城市过去二十年变了很多。', trunk: 'The city has changed', peel: 'where I was born 定语从句修饰 city；over the past... 时间状语。' },
  { en: 'If it rains tomorrow, we will cancel the outdoor meeting.', zh: '如果明天下雨，我们就取消户外会议。', trunk: 'we will cancel the meeting', peel: 'If it rains tomorrow 条件状语从句。' },
  { en: 'Having finished his homework, the boy went out to play basketball.', zh: '做完作业后，男孩出去打篮球。', trunk: 'the boy went out', peel: 'Having finished... 现在分词完成式作时间状语，表“先做完”。' },
  { en: 'The fact that many people are worried about the environment stems from the growing awareness that human activities are causing irreversible damage.', zh: '许多人担忧环境这一事实，源于一种日益增长的意识——人类活动正在造成不可逆的破坏。', trunk: 'The fact stems from the awareness', peel: 'that many people... 同位语从句解释 fact；that human activities... 同位语从句解释 awareness。' },
  { en: 'She is the most diligent student that I have ever taught.', zh: '她是我教过的最勤奋的学生。', trunk: 'She is the student', peel: 'the most diligent 最高级；that I have ever taught 定语从句。' },
  { en: 'Despite the difficulties, they managed to complete the project on time.', zh: '尽管有困难，他们还是按时完成了项目。', trunk: 'they managed to complete the project', peel: 'Despite the difficulties 介词短语作让步状语。' },
  { en: 'The teacher told us that practice makes perfect.', zh: '老师告诉我们熟能生巧。', trunk: 'The teacher told us', peel: 'that practice makes perfect 宾语从句。' },
  { en: 'Reading books widely can not only broaden our knowledge but also improve our thinking.', zh: '广泛读书不仅能拓宽知识，还能提升思维。', trunk: 'Reading books can broaden and improve', peel: 'Reading books 动名词作主语；not only... but also 并列宾语。' },
  { en: 'The old man, who lives alone, enjoys feeding the birds in the park every morning.', zh: '那位独居的老人每天早晨喜欢喂公园里的鸟。', trunk: 'The old man enjoys feeding the birds', peel: 'who lives alone 非限制性定语从句；every morning 时间状语。' },
  { en: 'Before leaving for the airport, please make sure you have your passport.', zh: '出发去机场前，请确保带好了护照。', trunk: 'please make sure', peel: 'Before leaving... 时间状语；you have... 宾语从句。' },
  { en: 'It was not until midnight that he realized he had left the key at home.', zh: '直到半夜他才意识到把钥匙落在家里了。', trunk: 'he realized', peel: 'It was not until... that 强调句型；he had left... 宾语从句。' },
  { en: 'The research shows that people who exercise regularly tend to be happier.', zh: '研究表明经常锻炼的人往往更快乐。', trunk: 'The research shows', peel: 'that 宾语从句；其中 who exercise regularly 定语从句修饰 people。' },
  { en: 'My friend recommended a novel which was written by a young writer from France.', zh: '朋友推荐了一本年轻法国作家写的小说。', trunk: 'My friend recommended a novel', peel: 'which was written... 定语从句修饰 novel（被动语态）。' },
  { en: 'No matter how busy you are, you should spare some time for your family.', zh: '无论多忙，你都该抽时间陪家人。', trunk: 'you should spare time', peel: 'No matter how busy 让步状语从句。' },
  { en: 'The children were so excited that they could not fall asleep quickly.', zh: '孩子们兴奋得迟迟睡不着。', trunk: 'The children were excited', peel: 'so... that 结果状语从句。' },
  { en: 'By the time we arrived, the movie had already started.', zh: '我们到的时候电影已经开始了。', trunk: 'the movie had started', peel: 'By the time we arrived 时间状语从句；had started 过去完成时。' },
  { en: 'He suggested that we should take a different approach to solve the problem.', zh: '他建议我们换一种方法解决问题。', trunk: 'He suggested', peel: 'that 宾语从句（suggest 后用 should+动原）。' },
  { en: 'The museum, built in the 19th century, attracts millions of visitors each year.', zh: '这座建于19世纪的博物馆每年吸引数百万游客。', trunk: 'The museum attracts visitors', peel: 'built in the 19th century 过去分词作定语。' },
  { en: 'Whether we will go camping depends on the weather tomorrow.', zh: '我们是否去露营取决于明天的天气。', trunk: 'Whether we will go depends', peel: 'Whether 主语从句；on the weather 介词短语。' },
  { en: 'The police are looking for the man who stole the wallet from the old lady.', zh: '警察在找那个从老太太那偷钱包的男人。', trunk: 'The police are looking for the man', peel: 'who stole... 定语从句修饰 man。' },
  { en: 'To get a better job, she decided to study for a master\'s degree abroad.', zh: '为了找更好的工作，她决定出国读硕士。', trunk: 'she decided to study', peel: 'To get a better job 不定式作目的状语。' },
  { en: 'Although the task was difficult, the team completed it ahead of schedule.', zh: '尽管任务艰巨，团队还是提前完成了。', trunk: 'the team completed it', peel: 'Although the task was difficult 让步状语从句。' },
  { en: 'The professor\'s lecture, which lasted two hours, covered both theory and practice.', zh: '教授那场两小时的讲座涵盖了理论与实践。', trunk: 'The lecture covered theory and practice', peel: 'which lasted two hours 非限制性定语从句。' },
  { en: 'I was surprised to find that the small town had changed beyond recognition.', zh: '我惊讶地发现这个小镇变得认不出来了。', trunk: 'I was surprised', peel: 'to find... 原因状语；that 宾语从句。' },
  { en: 'Governments should take measures so that the environment can be protected.', zh: '政府应采取措施，好让环境得到保护。', trunk: 'Governments should take measures', peel: 'so that 目的状语从句（含被动 can be protected）。' },
  { en: 'The more you read, the more you will understand about the world.', zh: '你读得越多，对世界的理解就越多。', trunk: 'you read and you will understand', peel: 'The more..., the more... 比较状语从句结构。' },
  { en: 'It is believed that a balanced diet contributes to both physical and mental health.', zh: '人们相信均衡饮食有益于身心健康。', trunk: 'It is believed', peel: 'that 主语从句（it 形式主语，被动语态）。' },
  { en: 'The girl whose handwriting is the best in class was praised by the teacher.', zh: '班里字写得最好的女孩受到了老师表扬。', trunk: 'The girl was praised', peel: 'whose handwriting... 定语从句（whose 表所属）。' },
  { en: 'After the meeting ended, we went to a restaurant to discuss the plan further.', zh: '会议结束后，我们去餐厅进一步讨论计划。', trunk: 'we went to a restaurant', peel: 'After the meeting ended 时间状语；to discuss... 目的状语。' },
  { en: 'He was so absorbed in the game that he forgot to do his homework.', zh: '他太沉迷游戏，忘了做作业。', trunk: 'He was absorbed', peel: 'so... that 结果状语从句；in the game 介词短语。' },
  { en: 'The company where my mother works is planning to open a new branch.', zh: '我妈妈工作的公司正计划开新分店。', trunk: 'The company is planning', peel: 'where my mother works 定语从句修饰 company。' },
  { en: 'If I had known the truth earlier, I would have told you immediately.', zh: '要是我早点知道真相，就会立刻告诉你。', trunk: 'I would have told you', peel: 'If I had known 虚拟条件句（对过去假设）。' },
  { en: 'The scientist spent years observing the stars before he made the discovery.', zh: '这位科学家花了多年观测星空，才有所发现。', trunk: 'The scientist spent years', peel: 'observing the stars 宾语补足（spend... doing）；before 时间状语。' },
  { en: 'Many students find it difficult to concentrate in a noisy environment.', zh: '许多学生发现在嘈杂环境里难集中注意力。', trunk: 'Many students find it difficult', peel: 'it 形式宾语；to concentrate... 真正宾语。' },
  { en: 'The bridge, damaged by the flood, is now being repaired by the workers.', zh: '被洪水损坏的桥现在正由工人抢修。', trunk: 'The bridge is being repaired', peel: 'damaged by the flood 过去分词定语；by the workers 动作执行者（被动）。' },
  { en: 'Whenever she feels stressed, she listens to soft music to relax.', zh: '每当她压力大，就听轻音乐放松。', trunk: 'she listens to music', peel: 'Whenever 时间状语从句；to relax 目的状语。' },
  { en: 'The report indicates that the economy is slowly recovering from the crisis.', zh: '报告显示经济正从危机中缓慢复苏。', trunk: 'The report indicates', peel: 'that 宾语从句；from the crisis 介词短语。' },
  { en: 'Rather than complain, we should try to find a solution to the problem.', zh: '与其抱怨，我们不如试着找解决办法。', trunk: 'we should try to find a solution', peel: 'Rather than complain 比较状语（带省略）。' },
  { en: 'The young man who saved the child from the river was awarded a medal.', zh: '那个从河里救了孩子的年轻人被授予奖章。', trunk: 'The young man was awarded a medal', peel: 'who saved... 定语从句；from the river 介词短语。' },
  { en: 'It took her three hours to finish the painting she had started yesterday.', zh: '她花了三小时完成昨天开始画的那幅画。', trunk: 'It took her three hours', peel: 'to finish... 真正主语（it 形式主语）；she had started 定语从句。' },
  { en: 'Unless you practice every day, you will not make real progress.', zh: '除非每天练习，否则你不会有真正进步。', trunk: 'you will not make progress', peel: 'Unless 条件状语从句（= if not）。' },
  { en: 'The book on the desk, which belongs to my brother, is about Chinese history.', zh: '桌上那本属于我弟弟的书是关于中国历史的。', trunk: 'The book is about history', peel: 'on the desk 介词短语定语；which belongs... 定语从句。' },
  { en: 'We were walking in the forest when we heard a strange noise.', zh: '我们正在林中散步，这时听到奇怪声响。', trunk: 'We were walking', peel: 'in the forest 地点状语；when 引导并列句（这时突然）。' },
  { en: 'The government has launched a campaign to encourage people to save energy.', zh: '政府发起了一项鼓励人们节能的运动。', trunk: 'The government has launched a campaign', peel: 'to encourage... 不定式作定语修饰 campaign。' },
  { en: 'Because of the heavy snow, all the flights were delayed for several hours.', zh: '因为大雪，所有航班延误了几个小时。', trunk: 'all the flights were delayed', peel: 'Because of the heavy snow 介词短语原因状语（被动）。' },
  { en: 'The letter that arrived this morning was from an old friend I had not seen for years.', zh: '今早到的那封信来自一位多年未见的老友。', trunk: 'The letter was from a friend', peel: 'that arrived 定语从句；I had not seen 省略关系词定语从句。' },
  { en: 'He spoke so loudly that everyone in the room could hear him clearly.', zh: '他讲得很大声，屋里每个人都听得清。', trunk: 'He spoke', peel: 'so... that 结果状语从句；in the room 地点状语。' },
  { en: 'The child pretended to be asleep when his mother came into the room.', zh: '妈妈进屋时，孩子假装睡着了。', trunk: 'The child pretended', peel: 'to be asleep 不定式作宾语；when 时间状语从句。' }
];

/* 语法选择题自测（基于上面 15 个语法点） */
window.ENG_GRAMMAR_QUIZ = [
  { q: '找出句子 "She reads books every day." 的时态：', options: ['一般过去时', '一般现在时', '现在完成时', '一般将来时'], answer: 1, explain: 'every day 是标志词，主语三单 reads，属一般现在时。' },
  { q: '“There ___ a book and two pens on the desk.” 应填：', options: ['is', 'are', 'be', 'am'], answer: 0, explain: 'There be 就近原则，靠近的 a book 是单数，用 is。' },
  { q: '被动语态 "The book was written by Lu Xun." 中 was written 是：', options: ['主动语态', 'be + 过去分词', '情态动词', '比较级'], answer: 1, explain: '被动 = be 动词 + 过去分词，was written 即此结构。' },
  { q: '定语从句 "The book that I bought is new." 中 that 指：', options: ['人', '物（book）', '时间', '地点'], answer: 1, explain: 'that 修饰前面的 the book（物），在从句中作 bought 的宾语。' },
  { q: '“He can swim.” 中 can 是：', options: ['实义动词', '情态动词', '系动词', '介词'], answer: 1, explain: 'can 是情态动词，后接动词原形 swim。' },
  { q: '“The more we read, the wiser we become.” 用了：', options: ['比较级结构', '被动语态', '定语从句', '宾语从句'], answer: 0, explain: '“the + 比较级…, the + 比较级…” 表示“越…越…”。' },
  { q: '“I think (that) he is right.” 中 that 引导：', options: ['定语从句', '宾语从句', '同位语从句', '状语从句'], answer: 1, explain: 'think 后的 that 从句作宾语，即宾语从句。' },
  { q: '“The boy playing basketball is my brother.” 中 playing 是：', options: ['谓语', '非谓语动词（现在分词作定语）', '被动语态', '情态动词'], answer: 1, explain: 'playing 是非谓语动词，作定语修饰 boy，不是谓语。' },
  { q: '“a piece of advice” 中 advice 是：', options: ['可数名词', '不可数名词', '动词', '形容词'], answer: 1, explain: 'advice 不可数，表“一条建议”用 a piece of。' },
  { q: '“Not only does he sing, but also he dances.” 倒装出现在：', options: ['but also 后', 'Not only 后', '句末', '没有倒装'], answer: 1, explain: 'Not only 置首引发半倒装，助动词 does 提前到主语 he 前。' }
];
